// CSV exporters for QuickBooks 3-col / 4-col, Xero, and a generic
// flat profile. All output uses CRLF line endings (Windows-friendly,
// QuickBooks-friendly), unconditionally quotes fields containing
// commas, quotes, or newlines, and emits dates in en-US MDY (ADR-014).

import { centsToDecimal } from '../ofx/ast.js';

export type CsvTemplate = 'qbo3' | 'qbo4' | 'xero' | 'generic';

export interface CsvRow {
  postedDate: string; // YYYY-MM-DD
  description: string;
  amountCents: bigint;
  // generic-only fields below; the four QBO/Xero templates ignore them.
  runningBalanceCents?: bigint | null | undefined;
  checkNumber?: string | undefined;
  trntype?: string | undefined;
  fitid?: string | undefined;
  memo?: string | undefined;
  // Check payee read off the cancelled-check image. Fills the Xero Payee
  // column and a dedicated generic-CSV Payee column; falls back to the
  // description when absent.
  payee?: string | null | undefined;
  // Phase 33 — generic-only enrichment columns. Empty strings render as
  // a blank cell so the column always appears in the header (the
  // generic CSV is the documented power-user export and operators who
  // don't run enrichment still want stable column ordering).
  cleansedDescription?: string | null | undefined;
  category?: string | null | undefined;
}

const escapeCell = (s: string): string => {
  if (/[",\r\n]/.test(s)) return `"${s.replaceAll('"', '""')}"`;
  return s;
};

const toCsv = (rows: string[][]): string =>
  rows.map((r) => r.map(escapeCell).join(',')).join('\r\n') + '\r\n';

const isoToMdy = (iso: string): string => {
  const [yyyy, mm, dd] = iso.split('-');
  return `${mm}/${dd}/${yyyy}`;
};

// QBO 3-column: Date, Description, Amount (signed; debits negative)
const renderQbo3 = (rows: CsvRow[]): string => {
  const out: string[][] = [['Date', 'Description', 'Amount']];
  for (const r of rows) {
    out.push([isoToMdy(r.postedDate), r.description, centsToDecimal(r.amountCents)]);
  }
  return toCsv(out);
};

// QBO 4-column: Date, Description, Credit, Debit (positive in its column,
// the other column blank). Per BuildPlan Phase 20 item 2 — Credit is the
// LEFT column, Debit is the RIGHT column.
const renderQbo4 = (rows: CsvRow[]): string => {
  const out: string[][] = [['Date', 'Description', 'Credit', 'Debit']];
  for (const r of rows) {
    const negative = r.amountCents < 0n;
    const abs = negative ? -r.amountCents : r.amountCents;
    out.push([
      isoToMdy(r.postedDate),
      r.description,
      negative ? '' : centsToDecimal(abs),
      negative ? centsToDecimal(abs) : '',
    ]);
  }
  return toCsv(out);
};

// Xero: *Date, *Amount, Payee, Description, Reference (5 columns per spec).
// Payee uses the check payee when one was read off the check image, else the
// description (Xero deduplicates Payee/Description); the optional check number
// or memo goes into Reference.
const renderXero = (rows: CsvRow[]): string => {
  const out: string[][] = [['*Date', '*Amount', 'Payee', 'Description', 'Reference']];
  for (const r of rows) {
    const reference = r.checkNumber ?? r.memo ?? '';
    const payee = r.payee && r.payee.length > 0 ? r.payee : r.description;
    out.push([
      isoToMdy(r.postedDate),
      centsToDecimal(r.amountCents),
      payee,
      r.description,
      reference,
    ]);
  }
  return toCsv(out);
};

// Generic: full denormalized row — Date, Description, Amount,
// RunningBalance, CheckNumber, Payee, TRNTYPE, FITID, CleansedDescription,
// Category. Used for spreadsheet review and as the audit-friendly
// fallback. Phase 20 item 2; Phase 33 enrichment columns.
const renderGeneric = (rows: CsvRow[]): string => {
  const out: string[][] = [
    [
      'Date',
      'Description',
      'Amount',
      'RunningBalance',
      'CheckNumber',
      'Payee',
      'TRNTYPE',
      'FITID',
      'CleansedDescription',
      'Category',
    ],
  ];
  for (const r of rows) {
    out.push([
      isoToMdy(r.postedDate),
      r.description,
      centsToDecimal(r.amountCents),
      r.runningBalanceCents == null ? '' : centsToDecimal(r.runningBalanceCents),
      r.checkNumber ?? '',
      r.payee ?? '',
      r.trntype ?? '',
      r.fitid ?? '',
      r.cleansedDescription ?? '',
      r.category ?? '',
    ]);
  }
  return toCsv(out);
};

export interface RenderCsvOptions {
  // Optional leading `# Generated by ...` line. Off by default for QBO/Xero
  // (their importers don't tolerate prefix lines); on for `generic`.
  // (Phase 20 item 18.)
  headerComment?: string;
}

// UTF-8 BOM (U+FEFF, bytes EF BB BF). Excel on Windows ignores HTTP
// `charset=utf-8` once the file is on disk and falls back to the
// system codepage (Windows-1252), which mojibakes any non-ASCII byte
// (em dashes, accented merchants). A leading BOM forces Excel — and
// every other modern spreadsheet importer (Google Sheets, Numbers,
// Xero, QuickBooks Online CSV import) — into UTF-8 mode.
const UTF8_BOM = '﻿';

export const renderCsv = (
  template: CsvTemplate,
  rows: CsvRow[],
  opts: RenderCsvOptions = {},
): string => {
  const body = ((): string => {
    switch (template) {
      case 'qbo3':
        return renderQbo3(rows);
      case 'qbo4':
        return renderQbo4(rows);
      case 'xero':
        return renderXero(rows);
      case 'generic':
        return renderGeneric(rows);
    }
  })();
  const withHeader =
    opts.headerComment && template === 'generic' ? `# ${opts.headerComment}\r\n${body}` : body;
  return UTF8_BOM + withHeader;
};
