// CSV exporters for QuickBooks 3-col / 4-col, Xero, and a generic
// flat profile. All output uses CRLF line endings (Windows-friendly,
// QuickBooks-friendly), unconditionally quotes fields containing
// commas, quotes, or newlines, and emits dates in en-US MDY (ADR-014).

import { centsToDecimal } from '../ofx/ast.js';

export type CsvTemplate = 'qbo3' | 'qbo4' | 'xero' | 'generic';

export interface CsvRow {
  postedDate: string; // YYYY-MM-DD
  description: string;
  amountCents: bigint;
  // generic-only fields below; the four QBO/Xero templates ignore them.
  runningBalanceCents?: bigint | null | undefined;
  checkNumber?: string | undefined;
  trntype?: string | undefined;
  fitid?: string | undefined;
  memo?: string | undefined;
}

const escapeCell = (s: string): string => {
  if (/[",\r\n]/.test(s)) return `"${s.replaceAll('"', '""')}"`;
  return s;
};

const toCsv = (rows: string[][]): string =>
  rows.map((r) => r.map(escapeCell).join(',')).join('\r\n') + '\r\n';

const isoToMdy = (iso: string): string => {
  const [yyyy, mm, dd] = iso.split('-');
  return `${mm}/${dd}/${yyyy}`;
};

// QBO 3-column: Date, Description, Amount (signed; debits negative)
const renderQbo3 = (rows: CsvRow[]): string => {
  const out: string[][] = [['Date', 'Description', 'Amount']];
  for (const r of rows) {
    out.push([isoToMdy(r.postedDate), r.description, centsToDecimal(r.amountCents)]);
  }
  return toCsv(out);
};

// QBO 4-column: Date, Description, Credit, Debit (positive in its column,
// the other column blank). Per BuildPlan Phase 20 item 2 — Credit is the
// LEFT column, Debit is the RIGHT column.
const renderQbo4 = (rows: CsvRow[]): string => {
  const out: string[][] = [['Date', 'Description', 'Credit', 'Debit']];
  for (const r of rows) {
    const negative = r.amountCents < 0n;
    const abs = negative ? -r.amountCents : r.amountCents;
    out.push([
      isoToMdy(r.postedDate),
      r.description,
      negative ? '' : centsToDecimal(abs),
      negative ? centsToDecimal(abs) : '',
    ]);
  }
  return toCsv(out);
};

// Xero: *Date, *Amount, Payee, Description, Reference (5 columns per spec).
// Payee is the leading payee phrase; we use the description as both Payee
// and Description (Xero deduplicates), and place the optional check number
// or memo into Reference.
const renderXero = (rows: CsvRow[]): string => {
  const out: string[][] = [['*Date', '*Amount', 'Payee', 'Description', 'Reference']];
  for (const r of rows) {
    const reference = r.checkNumber ?? r.memo ?? '';
    out.push([
      isoToMdy(r.postedDate),
      centsToDecimal(r.amountCents),
      r.description,
      r.description,
      reference,
    ]);
  }
  return toCsv(out);
};

// Generic: full denormalized row — Date, Description, Amount,
// RunningBalance, CheckNumber, TRNTYPE, FITID. Used for spreadsheet
// review and as the audit-friendly fallback. Phase 20 item 2.
const renderGeneric = (rows: CsvRow[]): string => {
  const out: string[][] = [
    ['Date', 'Description', 'Amount', 'RunningBalance', 'CheckNumber', 'TRNTYPE', 'FITID'],
  ];
  for (const r of rows) {
    out.push([
      isoToMdy(r.postedDate),
      r.description,
      centsToDecimal(r.amountCents),
      r.runningBalanceCents == null ? '' : centsToDecimal(r.runningBalanceCents),
      r.checkNumber ?? '',
      r.trntype ?? '',
      r.fitid ?? '',
    ]);
  }
  return toCsv(out);
};

export interface RenderCsvOptions {
  // Optional leading `# Generated by ...` line. Off by default for QBO/Xero
  // (their importers don't tolerate prefix lines); on for `generic`.
  // (Phase 20 item 18.)
  headerComment?: string;
}

export const renderCsv = (
  template: CsvTemplate,
  rows: CsvRow[],
  opts: RenderCsvOptions = {},
): string => {
  const body = ((): string => {
    switch (template) {
      case 'qbo3':
        return renderQbo3(rows);
      case 'qbo4':
        return renderQbo4(rows);
      case 'xero':
        return renderXero(rows);
      case 'generic':
        return renderGeneric(rows);
    }
  })();
  if (opts.headerComment && template === 'generic') {
    return `# ${opts.headerComment}\r\n${body}`;
  }
  return body;
};
